### ISSUE TITLE
SimIiwaDriver Not Found Error

### ISSUE THREAD

**Issue by omeym** [RussTedrake/manipulation#431]
Hi,
I'm trying to use the manipulation repository for my work on Ubuntu 24.04. The manipulation package is installed in a venv and python version is 3.12.
I am receiving the following error: 
File "/home/rp/omey_ws/manipulation/manipulation/station.py", line 17, in <module>
    from pydrake.all import (
ImportError: cannot import name 'SimIiwaDriver' from 'pydrake.all' (/home/rp/omey_ws/omeym-drake/lib/python3.12/site-packages/pydrake/all.py)

I have a similar version of the code working without any issues on another Ubuntu 24.04 system and in a conda environment. Not sure what the issue is.

Thanks.
